#+OPTIONS: num:1 toc:2


* Chapter 1

** Exercise 1.1-1 

Give a real-world example that requires sorting or a real-world example
that requires computing a convex hull.

*** Solution:

Language Processing, etc. 

Tips: About Cover_hull(https://en.wikipedia.org/wiki/Convex_hull)

Actullay, in clrs, Chapter 33 considers a few problems in computational geometry. After dis-
cussing basic primitives of computational geometry, the chapter shows how to use
a “sweeping” method to efficiently determine whether a set of line segments con-
tains any intersections. Two clever algorithms for finding the convex hull of a
set of points—Graham’s scan and Jarvis’s march—also illustrate the power of
sweeping methods. The chapter closes with an efficient algorithm for finding the
closest pair from among a given set of points in the plane.

** Exercise 1.1-2

Other than speed, what other measures of efficiency might one use in a
real-world setting?

*** Solution:

Space, etc.

** Exercise 1.1-3

Select a data structure that you have seen previously, and discuss its strengths
and limitations.

*** Solution:

linked list and ordered list. The first one can be smaller but harder to find
elements in the middle, and can be made dynamic. The second one is easy to
implement but the space it needs is usually static.

** Exercise 1.1-4

How are the shortest-path and traveling-salesman problems given above similar?
How are they different?

*** Solution:

They are similar because both problem are intended to find the something
shortest. However, the first one only intended to find a single path while the
second one may include several steps in finding a single path.


** Exercise 1.1-5

Come up with a real-world problem in which only the best solution will do. Then
come up with one in which a solution that is “approximately” the best is good
enough

*** Solution:

*Only the best*: Sorting a phone book. Making a dictinary or something like that, etc.

*Approximate is okay*: Try to maximum the profit. Find some company to invest, etc.
